config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'home#index'
   get 'home/about'
 
  
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
    
    belongs_to :user
   
        has_attached_file :image, :styles => { :medium => "300X300>", :thumb =>
    "100X100>" }
    
        validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable, 
    :recoverable, :rememberable, :trackable, :validatable
    has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

def about
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
def about
end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]  
  before_action :correct_user, only: [:edit, :update, :destroy]


  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
   
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def correct_user
    @pin = current_user.pins.find_by(id: params[:id])
    redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>-->
       <li><%= link_to 'Home', root_path %></li> 
        <li><%= link_to 'My Pins', pins_path%></li>
        
    <% if user_signed_in? %>
    <%= javascript_include_tag :defaults %>    
    
       

        <li><%= link_to 'Pin It', new_pin_path%></li>
        
        
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Browse <span class="caret"></span></a>
          <ul class="dropdown-menu">
             <li><a href="#">Popular</a></li>
            <li><a href="#">Everything</a></li>
            <li><a href="#">Art</a></li>
            <li><a href="#">Books</a></li>
            <li><a href="#">Cars and Motorcycles</a></li>
            <li><a href="#">Education</a></li>
            <li><a href="#">Electronics</a></li>
            <li><a href="#">Gardening</a></li>
            <li><a href="#">Hair and Beauty</a></li>
            <li><a href="#">Health and fitness</a></li>
            <li><a href="#">Holidays</a></li>
            <li><a href="#">Home decor</a></li>
            <li><a href="#">Kids </a></li>
            <li><a href="#">Men's fashion</a></li>
            <li><a href="#">Outdoors</a></li>
            <li><a href="#">Party Supplies</a></li>
            <li><a href="#">Pets</a></li>
            <li><a href="#">Weddings</a></li>
            <li><a href="#">Women's fashion</a></li>
            
          </ul>
        </li>
      </ul>
      
      
      
      
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
    
    <% else %>
            <li><%= link_to "Join", new_user_registration_path %>
            <li><%= link_to "Login", new_user_session_path %>
            
    <% end %>
            <li><%= link_to 'Edit Profile', edit_user_registration_path%></li>
            <li role="separator" class="divider"></li>
          
            <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
            <!--<li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>-->
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>About Dooptopia</h1>
<p>You'll never do your online shopping the same way again.</p>
    
<p>Dooptopia takes the work out of saving on your favorites online. Let the savings come to you and you'll shop smarter from now on. 
Dooptopia works with online retailers via their direct participation to offer you the best alternatives, savings, and coupons available on the web. We provide you informatin through our direct partnerships with etailers and online retailers and doing the hard work of deep scraping the internet with the help of services like Kimono and 80legs &copy; . </p>

app/views/home/index.html.erb
<div class="jumbotron">
<h1>Dooptopia.</h1>
<p>This pinterest-style app provides an organized space to catalogue all of the products you dream of from home-improvement, to make-up, to fashion and jewelry and notify you when a cheaper, similar alternative exists. 
Also, set up price comparison and coupon notifications that save you $$. You can purchase right from the app! 
So, go ahead and dream, indulge, oogle and doop it. </p>

<p>Make Your Dreams Your Reality; Reasonably.</p>
<%= link_to 'About Us', home_about_path, class: 'btn btn-primary' %>
<%= link_to 'Home', root_path, class: 'btn btn-primary' %>
 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Debrena's Workspace</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>


<%=render'home/header'%>

<div class='container'>
<% flash.each do |name, msg| %>
 <%= content_tag( :div, msg, class: "alert alert-info") %>
<% end %>
</div>

<div class="container">
<%= yield %>
</div>
  
</body>
</html>

app/views/pins/_form.html.erb
<%= form_for@pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <%= f.label :description %><br>
  <%= f.text_field :description %>
</div>
<div class="form-group">
  <%= f.label :image %>
  <%= f.file_field :image, class: "form-control" %>
</div>

<div class="actions">
  <%= f.submit class: 'btn btn-primary'%>
</div>
<% end %>

<div class="panel-footer">
</div>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading"><h1>Listing Pins</h1></div>
  <div class="panel-body">
</div>


<div class="container">
<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= pin.description %></td>
        <td><%= image_tag pin.image.url( :medium) %></td>
        <td><%= link_to 'Show', pin, class:'btn btn-default' %></td> 
          <% if pin.user == current_user %>
        <td><%= link_to 'Edit', edit_pin_path(pin), class:'btn btn-default' %></td>
        <td><%= link_to 'Destroy', pin, method: :delete, class:'btn btn-default', data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
  <div class="panel-footer"> 
<%= link_to 'New Pin', new_pin_path, class:'btn btn-default' %>
  </div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %><br/>
  <%= image_tag @pin.image.url(:medium) %>
</p>

<% if @pin.user == current_user %>
<%= link_to 'Edit', edit_pin_path(@pin) %> |
<% end %>



<%= link_to 'Back', pins_path %>